### PR TITLE
begin porting from open3d

### PR DESCRIPTION
**Pull request by zeffii**
it might take a day or so to get the head around this.

### CODE REVIEW

**Review by Marcus-Richmond — APPROVED** [review]

**Comment by Marcus-Richmond** [comment]
Ok, this is really starting to take shape! I now see the GIS category in the Sverchok add menu: 

image

**So how can we add nodes to this GIS category?**

Just thinking aloud here......I am looking through the code now, trying to understand what's going on. Looks like the "GIS" category was added from the [menu.py](https://github.com/Marcus-Richmond/sverchok-gis-nodes/blob/main/menu.py) file in the `NODEVIEW_MT_GIS` class. Also looks like the code that actually runs in this class is leftover from the Open3D template and commented out: 

```
class NODEVIEW_MT_GIS(bpy.types.Menu):
    bl_label = "GIS"

    def draw(self, context):
        layout = self.layout
        # layout.operator_context = 'INVOKE_REGION_WIN'
        # if o3d is None:
        #     layout.operator('node.sv_ex_pip_install', text="Install Open3d Library with PIP").package = "open3d"
        # else:
        #     layout_draw_categories(self.layout, self.bl_label, node_cats['Utils'])
        #     layout.menu("NODEVIEW_MT_Open3DPointCloudMenu")
        #     layout.menu("NODEVIEW_MT_Open3DTriangleMeshMenu")
        # layout.menu("NODEVIEW_MT_Open3DPointCloudMenu")
```

I'm guessing this was done since the code here relies on the Open3d library? I am going to mess around with this and see what happens.

**Comment by Marcus-Richmond** [comment]
[Check this out](https://github.com/Marcus-Richmond/sverchok-gis-nodes/blob/main/menu.py)! I managed to get the nodes to appear in the GIS category in the add node menu by making some minor changes to menu.py. I see that the `NODEVIEW_MT_GIS` adds nodes to the category, it now looks like this: 

```
class NODEVIEW_MT_GIS(bpy.types.Menu):
    bl_label = "GIS"

    def draw(self, context):
        layout = self.layout
        # layout.operator_context = 'INVOKE_REGION_WIN'
        # if o3d is None:
        #     layout.operator('node.sv_ex_pip_install', text="Install Open3d Library with PIP").package = "open3d"
        # else:
        #     layout_draw_categories(self.layout, self.bl_label, node_cats['Utils'])
        #     layout.menu("NODEVIEW_MT_Open3DPointCloudMenu")
        #     layout.menu("NODEVIEW_MT_Open3DTriangleMeshMenu")
        # layout.menu("NODEVIEW_MT_Open3DPointCloudMenu")

        layout_draw_categories(self.layout, self.bl_label, node_cats['General GIS'])
        # layout.menu("NODEVIEW_MT_GISImportAttributeMenu")
```

Through trial and error I also saw that the line `layout.menu("NODEVIEW_MT_GISImportAttributeMenu")` will add a subcategory, and relies upon the `menu_classes` list looking like:

```
menu_classes = [
    make_class('ImportAttribute', 'Import Attribute Node')
    # make_class('PointCloud', 'Point Cloud'),
    # make_class('TriangleMesh', 'Triangle Mesh')
    ]
```

image

This is very exciting! The addon template/OOP stuff is really starting to click.

**Comment by zeffii** [comment]
I can't get this addon to enable in Blender :)  so im coding "blind" :)

my advantage is that I wrote large portions of the code that Sverchok uses to load itself into memory,  seeing the kind of code that a sverchok-addon has to introduce to get added to Sverchok is a bit disappointing. If there is ever a rewrite of Sverchok's  startup code we will want to zoom out and make it easier for 3rd party authors to do this.

I didn't intend for you to merge the branch, but if this lets you progress on your own for a bit great. Questions welcome.

**Comment by Marcus-Richmond** [comment]
Ah yea, I had been struggling to get the main branch that I started working, so the sv_basic branch provided a better starting point. That makes me think of a couple questions too:

- When should I merge the changes in the branch you are working on? 
- Should I start my own branch to test and experiment with? I'm guessing the answer is yes, but I'm wondering if this will cause confusion or maybe duplication of efforts.

**Comment by zeffii** [comment]
in this early stage any "duplication of effort" is probably going to be a learning experience, rather than a complete waste of time (although it might seem that way).

When i add a pullrequest and mark it as "draft", it suggests that one or more details are not as they should be and it's probably unwise to merge without pulling down the branch and switching to it to test. There's usually a good reason to label it "draft", i'll try to be more explicit in future.

as this progresses the "internals" (the plumbing to load the addon and register all things blender needs) will settle down and pretty much stay that way indefinitely. It will rarely need changing. I hope that point is soon, and focus can go to the thing we're all here for;  Nodes.

**Pull request merged**
