### PR TITLE
revert to open3d template to start

### PR DESCRIPTION
**Pull request by zeffii**
this is a work in progress. The aim is to make the `__init__.py` file a little less in-your-face, and abstract most of it into utilities/devops

- [ ] redux init
- [x] dependancies
- [x] nodes
- [x] utils
- [ ] sockets?
- [ ] settings
- [ ] flawless reload (f8)
    - [x] node reload does work
    - [ ] eco system reload

### CODE REVIEW

**Comment by zeffii** [comment]
@Marcus-Richmond  the template is mostly working now, i've pulled in your version of these nodes. I think this reaches parity with the open3d template. Aside from maybe a few awkward register/unregister things, this will be close to the starting point for doing a few new nodes. Soon.

**Comment by zeffii** [comment]
The current order in which things are loaded into memory makes it cumbersome to automatically generate the `node index` (the category list of `<folder.node_file>, <ClassName>`). So i'm keeping the `node index` as a manually filled in feature. This also allows you to define the order in which nodes appear in the menus.

i'll get some time lateron to add a few useful nodes, that let you interoperate with existing sverchok nodes. The goal is to provide a set of nodes that don't assume any specific types of layers/features in the imported gis data.

**Comment by zeffii** [comment]
also... i find the current way of defining the node class with an extra indentation, a little bit clumsy to look at. It should not matter for the node definition whether the user has the correct libraries installed. This i will fix sooner rather than later.

**Comment by zeffii** [comment]
image

**Comment by zeffii** [comment]
you may wish to merge this to master, and start from here : )

**Comment by Marcus-Richmond** [comment]
Nice! The progress you are making on this is really exciting!

So, were these changes already merged? Sorry I hadn't been keeping up with this over the last couple of days, but looks like these changes are in master? 

Thanks for the patience as I try to learn Sverchok, OOP, blender addons, and github haha.

**Comment by zeffii** [comment]
I had more time than I thought. i merged these and subsequent changes from the `redux_architecture` branch, because I felt it was necessary to provide a tidier entry point. It seems that was mostly possible, but i'll keep interrogating it.

**Pull request merged**
